### PR TITLE
fix: evaluates perms regular expression when applying permissions

### LINKED ISSUE #45: Regex matching for permissions is broken
```nix
{
  inputs.nix2container.url = "github:nlewo/nix2container";
  inputs.nixpkgs.follows = "nix2container/nixpkgs";

  outputs = { self, nixpkgs, nix2container }:
    let
      pkgs = import nixpkgs { system = "aarch64-linux"; };
      n2c = nix2container.packages.aarch64-linux.nix2container;
      entrypoint = pkgs.writeShellApplication {
        name = "entrypoint";
        text = ''
          echo "Hello, world!"
        '';
      };
      test = pkgs.runCommand "test" { } ''
        mkdir -p $out/tmp
        touch $out/tmp/test1.txt
        touch $out/tmp/test2.txt
      '';
    in
    {
      packages.aarch64-linux.hello = n2c.buildImage {
        maxLayers = 100;
        name = "hello";
        config = {
          entrypoint = [ "${entrypoint}/bin/entrypoint" ];
        };
        copyToRoot = [ test pkgs.bash pkgs.coreutils ];
        perms = [
          {
            path = test;
            regex = "foobar";
            mode = "0777";
          }
        ];
      };
    };
}
```

Inside the resulting container:

```
bash-5.1# ls -la /tmp
total 8
drwxrwxrwx 2 0 0 4096 Jan  1  1970 .
drwxr-xr-x 1 0 0 4096 Sep 21 17:20 ..
-rwxrwxrwx 1 0 0    0 Jan  1  1970 test1.txt
-rwxrwxrwx 1 0 0    0 Jan  1  1970 test2.txt
```

The regex expression isn't being evaluated. The current behavior seems to apply permissions to every path in the closure.

### PR DESCRIPTION
**Pull request by jmgilman**
Fixes #45 

I ran the same sample code provided in the issue with this fix applied and got the expected results (no file permissions modified).

### CODE REVIEW

**Comment by nlewo** [comment]
Thanks for the fix!
I added a non regression test.

**Comment by nlewo** [comment]
@jmgilman arf, it seems the pulled image hash currently depends on the architecture of the machine running the tests. I don't know what we have to do exactly but to move forward on this PR, could you remove the commit updating the image hash?

Maybe we should explicitly specify x86 arch for the alpine image.

**Comment by jmgilman** [comment]
I tried explicitly putting in the architecture:

```
{
alpine = nix2container.pullImage {
    imageName = "alpine";
    imageDigest = "sha256:115731bab0862031b44766733890091c17924f9b7781b79997f5f163be262178";
    arch = "x86_64";
    sha256 = "sha256-o4GvFCq6pvzASvlI5BLnk+Y4UN6qKL2dowuT0cp8q7Q=";
  };
}
```

But I'm getting:

```
FATA[0001] choosing an image from manifest list docker://alpine@sha256:115731bab0862031b44766733890091c17924f9b7781b79997f5f163be262178: no image found in manifest list for architecture x86_64, variant "", OS linux
```

**Comment by jmgilman** [comment]
Nevermind, I'm just being dumb :) It's `amd64` not `x86_64`. That appears to fix the example.

**Comment by nlewo** [comment]
Thank jou @jmgilman !

**Pull request merged**
