### PR TITLE
Fixes #92: Make nix-user example work (including flakes)

### LINKED ISSUE #92: `nix-user-flakes`: `nix run` results in SSL connect error (35)
The [nix-user.nix](https://github.com/nlewo/nix2container/blob/master/examples/nix-user.nix) example seems to miss some setup step to make HTTPS work in the container.

I assume that "something" is missing e.g. in `/etc`.

# Reproducing the problem

If I use a [slightly modified version of the container](https://gitlab.com/nexxiot-labs/nix-user-container) so that I can use flakes and have bash in the entry point, I get:

```
❯ nix run git+https://gitlab.com/nexxiot-labs/nix-user-container#curl.copyToDockerDaemon \
  && docker run -it nix-user-flakes
Copy to Docker daemon image curl:latest
Getting image source signatures
Copying blob b11cc9fe06f2 done  
Copying config 667d3ab77c done  
Writing manifest to image destination
Running checks against store uri: local
[PASS] PATH contains only one nix version.
[PASS] All profiles are gcroots.
[PASS] Client protocol matches store protocol.
[INFO] You are trusted by store uri: local
total 24
drwxr-xr-x  1 user user 4096 Jan  1  1970 .
drwxr-xr-x  1    0    0 4096 Nov  3 12:24 ..
drwxr-xr-x 56 user user 4096 Jan  1  1970 store
drwxr-xr-x  1 user user 4096 Jan  1  1970 var
bash-5.2$ nix run nixpkgs#hello
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 315 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 513 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 1202 ms
warning: error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35); retrying in 2146 ms
error: unable to download 'https://channels.nixos.org/flake-registry.json': SSL connect error (35)
bash-5.2$ 
```

# Minimal curl example

One can reproduce the same error just using a container with curl:

```
❯ nix run git+https://gitlab.com/nexxiot-labs/nix-user-container#curl.copyToDockerDaemon \
  && docker run -it curl https://nixos.org

Copy to Docker daemon image curl:latest
Getting image source signatures
Copying blob b11cc9fe06f2 done  
Copying config 667d3ab77c done  
Writing manifest to image destination
curl: (35) OpenSSL/3.0.11: error:16000069:STORE routines::unregistered scheme
```

### What I tested

I originally tested a more elaborate setup that creates the nix config in `/etc`
and also tries to link `cacert` into etc... Doesn't make a difference as far as I can see.

```nix
  let
    user = "user";
    group = "user";
    uid = "1000";
    gid = "1000";

    mkUser = nixpkgs.runCommand "mkUser" {} ''
      mkdir -p $out/etc/{pam.d,nix}

      echo "${user}:x:${uid}:${gid}::" > $out/etc/passwd
      echo "${user}:!x:::::::" > $out/etc/shadow

      echo "${group}:x:${gid}:" > $out/etc/group
      echo "${group}:x::" > $out/etc/gshadow

      cat > $out/etc/pam.d/other <<EOF
      account sufficient pam_unix.so
      auth sufficient pam_rootok.so
      password requisite pam_unix.so nullok sha512
      session required pam_unix.so
      EOF

      cat > $out/etc/nix/nix.conf <<EOF
      experimental-features = nix-command flakes repl-flake
      max-jobs = auto
      extra-nix-path = nixpkgs=flake:nixpkgs
      max-silent-time = 10
      fsync-metadata = false
      EOF

      touch $out/etc/login.defs
      mkdir -p $out/home/${user}
    '';

    mkHome = nixpkgs.runCommand "mkHome" {} ''
      mkdir -p $out/home/${user}
    '';
  in
    nix2container.buildImage {
      name = "nix-user";
      tag = "latest";

      initializeNixDatabase = true;
      nixUid = l.toInt uid;
      nixGid = l.toInt gid;

      copyToRoot = [
        (nixpkgs.buildEnv {
          name = "root";
          paths = with nixpkgs; [coreutils nix openssl curl mkUser strace cacert];
          pathsToLink = ["/bin" "/etc" "/lib"];
        })
        mkHome
      ];

      perms = [
        {
          path = mkHome;
          regex = "/home/${user}";
          mode = "0744";
          uid = l.toInt uid;
          gid = l.toInt gid;
          uname = user;
          gname = group;
        }
      ];

      config = {
        Entrypoint = ["${nixpkgs.bash}/bin/bash"];
        User = "user";
        WorkingDir = "/home/user";
        Env = [
          "HOME=/home/user"
          "NIX_PAGER=cat"
          "USER=user"
        ];
      };
    };
```

### PR DESCRIPTION
**Pull request by kolloch**
Makes executing `nix` within the `nix-user` container possible :)

```
/thirdparty/nix2container master                                                                                                                                       base 14:27:00
❯ nix run .\#examples.nix-user.copyToDockerDaemon && docker run -it nix-user:latest
Copy to Docker daemon image nix-user:latest
Getting image source signatures
Copying blob a24921896e21 done  
Copying config ff83ffb7fb done  
Writing manifest to image destination
Running checks against store uri: local
[PASS] PATH contains only one nix version.
[PASS] All profiles are gcroots.
[PASS] Client protocol matches store protocol.
[INFO] You are trusted by store uri: local
total 24
drwxr-xr-x  1 user user 4096 Jan  1  1970 .
drwxr-xr-x  1    0    0 4096 Nov  3 13:28 ..
drwxr-xr-x 54 user user 4096 Jan  1  1970 store
drwxr-xr-x  1 user user 4096 Jan  1  1970 var
bash-5.2$ nix run nixpkgs#hello
Hello, world!
bash-5.2$ 
```

### CODE REVIEW

**Review by nlewo — COMMENTED** [review]
Hello @kolloch,

Thanks for these fixes!

I would prefer to keep the nix-user example as simple as possible. For instance, I don't think we should enable flakes since it's not related to the nix-user example itself.
Also, this example is used as a kind of unit test by the nix2container test suite (in the `./tests` project directoy).

What I understand is that you would like to have an example of a fully working nix image which seems to be relevant!
So, maybe we could rename the `nix.nix` to `nix-database.nix` and create a new `nix.nix` example with a fully working nix image (users, flakes, SSL, ...). Also, we should add a test for this new image but I could help on this part since we will have to make some tradeoff (no internet for instance).

wdyt?

**Comment by kolloch** [comment]
Sure! I don't mind to split it into another file.

To avoid misleading users such as me, I'd comment on the original file that some more steps are needed to make this work in practice. I mistook the example as a best practice recommendation and getting started basis.

If the "new" example will serve as the getting started basis, I'd keep adding to the nix.conf in there: It is a very common requirement if you want to build upon that example.

And I am all for tests. One think that might potentially make this difficult, is that for a meaninful test, you'd need to load the image into a docker runtime and execute some commands in it. Does your CI support that?

**Comment by nlewo** [comment]
>  I mistook the example as a best practice recommendation and getting started basis.

I'm sorry about this: this should no longer be in a example directory... Ideally we should have an example section and a test section but this kind of improvements takes time to implement :/ At least, currently, all "examples" are tested.  (btw, +1 for a comment in this file).

> If the "new" example will serve as the getting started basis, I'd keep adding to the nix.conf in there: It is a very common requirement if you want to build upon that example.

Agreed (and i'm also in favor of enabling flakes).

> One think that might potentially make this difficult, is that for a meaninful test, you'd need to load the image into a docker runtime and execute some commands in it. Does your CI support that?

Yes, the CI does that... in an impure way (see [this doc](https://github.com/nlewo/nix2container#run-the-tests)) but in practice it works pretty well (in the future, I'm planning to run this in a NixOS VM to make it pure).

**Comment by kolloch** [comment]
How shall I call the new directory then?

Or shall I rename `examples` to `testImages` or similar?

**Pull request closed without merging**
